In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/gigih 2.0/Covid Cases in Indonesia - Covid Cases in Indonesia.csv')
data.head(2)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (40,41,43,44,45,46) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Date,Location ISO Code,Location,New Cases,New Deaths,New Recovered,New Active Cases,Total Cases,Total Deaths,Total Recovered,...,region_id,Unnamed: 39,Province.1,Province (Data BPS),Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,region_id.1,Unnamed: 47
0,03/01/2020,ID-JK,DKI Jakarta,2,0,0,2,39,20,41,...,DJA,NaN,Aceh,Aceh,1.0,Aceh,NaN,NaN,ACE,0.0
1,03/02/2020,ID-JK,DKI Jakarta,2,0,0,2,41,20,41,...,DJA,NaN,Bali,Bali,1.0,Bali,NaN,NaN,BAL,NaN

In [ ]:
data.shape

(21759, 48)

In [ ]:
df=data[['Date','Province','Total Cases','Total Deaths','Total Recovered','Island','Total Districts','Total Urban Villages','Total Rural Villages','Population','Case Fatality Rate','Case Recovered Rate']]
df.head(10)

,Date,Province,Total Cases,Total Deaths,Total Recovered,Island,Total Districts,Total Urban Villages,Total Rural Villages,Population,Case Fatality Rate,Case Recovered Rate
0,03/01/2020,DKI Jakarta,39,20,41,Jawa,44,267.0,NaN,10846145,51.28%,105.13%
1,03/02/2020,DKI Jakarta,41,20,41,Jawa,44,267.0,NaN,10846145,48.78%,100.00%
2,03/02/2020,NaN,2,0,0,NaN,7230,8488.0,74953.0,265185520,0.00%,0.00%
3,03/02/2020,Riau,2,0,3,Sumatera,169,268.0,1591.0,6074100,0.00%,150.00%
4,03/03/2020,DKI Jakarta,43,20,41,Jawa,44,267.0,NaN,10846145,46.51%,95.35%
5,03/03/2020,NaN,2,0,0,NaN,7230,8488.0,74953.0,265185520,0.00%,0.00%
6,03/03/2020,Jawa Barat,1,1,8,Jawa,627,645.0,5312.0,45161325,100.00%,800.00%
7,03/03/2020,Riau,2,0,3,Sumatera,169,268.0,1591.0,6074100,0.00%,150.00%
8,03/04/2020,DKI Jakarta,45,20,41,Jawa,44,267.0,NaN,10846145,44.44%,91.11%
9,03/04/2020,NaN,2,0,0,NaN,7230,8488.0,74953.0,265185520,0.00%,0.00%

In [ ]:
df1=df["Province"].unique()
df1.shape
#f1

(35,)

## remove province that has null value

In [ ]:
new=df.dropna(subset=["Province"])
new["Province"].unique()

array(['DKI Jakarta', 'Riau', 'Jawa Barat', 'Banten', 'Jawa Tengah',
       'Sulawesi Tenggara', 'Bali', 'Kalimantan Timur',
       'Daerah Istimewa Yogyakarta', 'Sumatera Utara', 'Jawa Timur',
       'Kepulauan Riau', 'Sulawesi Selatan', 'Jambi', 'Maluku', 'Papua',
       'Maluku Utara', 'Sumatera Selatan', 'Aceh', 'Kalimantan Tengah',
       'Lampung', 'Sulawesi Tengah', 'Sulawesi Utara', 'Sumatera Barat',
       'Papua Barat', 'Kalimantan Utara', 'Sulawesi Barat',
       'Kalimantan Barat', 'Kalimantan Selatan',
       'Kepulauan Bangka Belitung', 'Bengkulu', 'Nusa Tenggara Barat',
       'Nusa Tenggara Timur', 'Gorontalo'], dtype=object)

In [ ]:
df["Total Urban Villages"] = df["Total Urban Villages"].replace(np.nan, 0);
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21759 entries, 0 to 21758
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  21759 non-null  object
 1   Province              21117 non-null  object
 2   Total Cases           21759 non-null  int64
 3   Total Deaths          21759 non-null  int64
 4   Total Recovered       21759 non-null  int64
 5   Island                21117 non-null  object
 6   Total Districts       21759 non-null  int64
 7   Total Urban Villages  21759 non-null  float64
 8   Total Rural Villages  21117 non-null  float64
 9   Population            21759 non-null  int64
 10  Case Fatality Rate    21759 non-null  object
 11  Case Recovered Rate   21759 non-null  object
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df["Total Rural Villages"] = df["Total Rural Villages"].replace(np.nan, 0);
df.info()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21759 entries, 0 to 21758
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  21759 non-null  object
 1   Province              21117 non-null  object
 2   Total Cases           21759 non-null  int64
 3   Total Deaths          21759 non-null  int64
 4   Total Recovered       21759 non-null  int64
 5   Island                21117 non-null  object
 6   Total Districts       21759 non-null  int64
 7   Total Urban Villages  21759 non-null  float64
 8   Total Rural Villages  21759 non-null  float64
 9   Population            21759 non-null  int64
 10  Case Fatality Rate    21759 non-null  object
 11  Case Recovered Rate   21759 non-null  object
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB

In [ ]:
change the data format "date"

In [ ]:
import datetime
covid["Date"] = covid["Date"].astype('datetime64[ns]');
covid.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21117 entries, 0 to 21757
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  21117 non-null  datetime64[ns]
 1   Province              21117 non-null  object
 2   Total Cases           21117 non-null  int64
 3   Total Deaths          21117 non-null  int64
 4   Total Recovered       21117 non-null  int64
 5   Island                21117 non-null  object
 6   Total Districts       21117 non-null  int64
 7   Total Urban Villages  21117 non-null  float64
 8   Total Rural Villages  21117 non-null  float64
 9   Population            21117 non-null  int64
 10  Case Fatality Rate    21117 non-null  object
 11  Case Recovered Rate   21117 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(5), object(4)
memory usage: 2.1+ MB

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

# retrieve the dataset in 2020

In [ ]:
c = covid[(covid['Date'] >= '2020-01-01') & (covid['Date'] <= '2020-12-31')]
c.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9713 entries, 0 to 10017
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  9713 non-null   datetime64[ns]
 1   Province              9713 non-null   object
 2   Total Cases           9713 non-null   int64
 3   Total Deaths          9713 non-null   int64
 4   Total Recovered       9713 non-null   int64
 5   Island                9713 non-null   object
 6   Total Districts       9713 non-null   int64
 7   Total Urban Villages  9713 non-null   float64
 8   Total Rural Villages  9713 non-null   float64
 9   Population            9713 non-null   int64
 10  Case Fatality Rate    9713 non-null   object
 11  Case Recovered Rate   9713 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(5), object(4)
memory usage: 986.5+ KB

In [ ]:
# from google.colab import files
# c.to_csv('cvd.csv', index=True)
# files.download('cvd.csv')

## Changing the writing of the province name to match the covid dataset so that it can be combined

In [ ]:
c["Province"]=c["Province"].replace(['Daerah Istimewa Yogyakarta','Kepulauan Bangka Belitung','Kepulauan Riau'],['DI Yogyakarta','Kep. Bangka Belitung','Kep. Riau'])
c

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,Date,Province,Total Cases,Total Deaths,Total Recovered,Island,Total Districts,Total Urban Villages,Total Rural Villages,Population,Case Fatality Rate,Case Recovered Rate
0,2020-03-01,DKI Jakarta,39,20,41,Jawa,44,267.0,0.0,10846145,51.28%,105.13%
1,2020-03-02,DKI Jakarta,41,20,41,Jawa,44,267.0,0.0,10846145,48.78%,100.00%
3,2020-03-02,Riau,2,0,3,Sumatera,169,268.0,1591.0,6074100,0.00%,150.00%
4,2020-03-03,DKI Jakarta,43,20,41,Jawa,44,267.0,0.0,10846145,46.51%,95.35%
6,2020-03-03,Jawa Barat,1,1,8,Jawa,627,645.0,5312.0,45161325,100.00%,800.00%
...,...,...,...,...,...,...,...,...,...,...,...,...
10013,2020-12-31,Sulawesi Tenggara,7907,147,6680,Sulawesi,219,377.0,1911.0,2635461,1.86%,84.48%
10014,2020-12-31,Sulawesi Utara,9670,310,7075,Sulawesi,171,332.0,1507.0,2641884,3.21%,73.16%
10015,2020-12-31,Sumatera Barat,23464,525,21816,Sumatera,179,230.0,928.0,5519245,2.24%,92.98%
10016,2020-12-31,Sumatera Selatan,11826,599,9362,Sumatera,241,387.0,2853.0,8217551,5.07%,79.16%
10017,2020-12-31,Sumatera Utara,18149,679,15391,Sumatera,450,693.0,5417.0,14874889,3.74%,84.80%

## grouping datasets by province and taking the total value of each variable

In [ ]:
cb=c.groupby(["Province"])
covid_data=cb[["Island","Total Cases","Total Deaths","Total Recovered","Population","Total Districts","Total Urban Villages","Total Rural Villages","Case Fatality Rate","Case Recovered Rate"]].max()
covid_data["Date"]="2020"
covid_data

,Island,Total Cases,Total Deaths,Total Recovered,Population,Total Districts,Total Urban Villages,Total Rural Villages,Case Fatality Rate,Case Recovered Rate,Date
Province,,,,,,,,,,,
Aceh,Sumatera,8746,358,7139,5247257,289,0.0,6497.0,9.09%,90.00%,2020
Bali,Nusa Tenggara,17593,516,16147,4216171,57,80.0,636.0,9.52%,92.85%,2020
Banten,Jawa,18154,525,15656,10722374,155,313.0,1238.0,9.72%,99.65%,2020
Bengkulu,Sumatera,3603,112,2556,1999539,129,172.0,1341.0,9.88%,83.46%,2020
DI Yogyakarta,Jawa,12155,259,8176,3631015,78,46.0,392.0,9.86%,88.32%,2020
DKI Jakarta,Jawa,183734,3270,164706,10846145,44,267.0,0.0,9.98%,95.74%,2020
Gorontalo,Sulawesi,3841,104,3311,1180651,77,72.0,657.0,8.33%,96.67%,2020
Jambi,Sumatera,3227,56,2318,3493357,141,163.0,1399.0,3.25%,81.29%,2020
Jawa Barat,Jawa,90216,1446,74928,45161325,627,645.0,5312.0,6.87%,83.05%,2020
Jawa Tengah,Jawa,82546,3627,56469,36364072,576,753.0,7809.0,90.91%,92.31%,2020
Jawa Timur,Jawa,84410,6399,75050,40479023,666,777.0,7724.0,9.91%,93.73%,2020
Kalimantan Barat,Kalimantan,3118,27,2744,5422814,174,99.0,2031.0,9.68%,99.44%,2020
Kalimantan Selatan,Kalimantan,15303,584,13800,4023049,153,144.0,1864.0,9.92%,92.27%,2020
Kalimantan Tengah,Kalimantan,9740,199,6487,2570289,136,139.0,1432.0,9.76%,89.39%,2020
Kalimantan Timur,Kalimantan,27076,743,22807,3552191,103,197.0,841.0,6.25%,86.61%,2020
Kalimantan Utara,Kalimantan,3794,57,2045,648407,53,35.0,447.0,6.25%,96.79%,2020
Kep. Bangka Belitung,Sumatera,2338,35,1718,1379767,47,82.0,309.0,9.09%,96.08%,2020
Kep. Riau,Sumatera,6995,171,6050,1929400,75,142.0,275.0,9.91%,90.06%,2020
Lampung,Sumatera,6276,275,4318,9095591,228,205.0,2435.0,9.52%,85.37%,2020
Maluku,Maluku,5722,71,4557,1847097,118,35.0,1198.0,8.70%,9.09%,2020
Maluku Utara,Maluku,2771,89,2355,1307803,116,118.0,1063.0,9.60%,90.67%,2020
Nusa Tenggara Barat,Nusa Tenggara,5664,261,4555,5270247,117,145.0,995.0,8.33%,9.87%,2020
Nusa Tenggara Timur,Nusa Tenggara,2167,49,1204,5411321,309,327.0,3026.0,4.35%,9.52%,2020
Papua,Papua,13209,156,7055,4340348,560,110.0,5411.0,8.75%,9.86%,2020
Papua Barat,Papua,5979,99,5449,1140701,218,95.0,1742.0,7.69%,91.14%,2020
Riau,Sumatera,24967,582,23079,6074100,169,268.0,1591.0,9.52%,92.61%,2020
Sulawesi Barat,Sulawesi,1941,34,1551,1559984,69,73.0,575.0,3.45%,9.59%,2020
Sulawesi Selatan,Sulawesi,31045,593,25750,9426885,311,792.0,2255.0,9.62%,90.44%,2020
Sulawesi Tengah,Sulawesi,3552,106,1865,2955567,175,175.0,1842.0,9.38%,92.35%,2020
Sulawesi Tenggara,Sulawesi,7907,147,6680,2635461,219,377.0,1911.0,7.41%,9.95%,2020
Sulawesi Utara,Sulawesi,9670,310,7075,2641884,171,332.0,1507.0,9.99%,85.30%,2020
Sumatera Barat,Sumatera,23464,525,21816,5519245,179,230.0,928.0,9.86%,93.37%,2020
Sumatera Selatan,Sumatera,11826,599,9362,8217551,241,387.0,2853.0,9.09%,9.09%,2020
Sumatera Utara,Sumatera,18149,679,15391,14874889,450,693.0,5417.0,9.91%,84.80%,2020

In [ ]:
covid_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34 entries, Aceh to Sumatera Utara
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Island                34 non-null     object
 1   Total Cases           34 non-null     int64
 2   Total Deaths          34 non-null     int64
 3   Total Recovered       34 non-null     int64
 4   Population            34 non-null     int64
 5   Total Districts       34 non-null     int64
 6   Total Urban Villages  34 non-null     float64
 7   Total Rural Villages  34 non-null     float64
 8   Case Fatality Rate    34 non-null     object
 9   Case Recovered Rate   34 non-null     object
 10  Date                  34 non-null     object
dtypes: float64(2), int64(5), object(4)
memory usage: 4.2+ KB

In [ ]:
# from google.colab import files
# x.to_csv('Covid2020.csv', index=True)
# files.download('Covid2020.csv')

In [ ]:
data2 = pd.read_csv('/content/drive/MyDrive/gigih 2.0/unemployment rate - Sheet1.csv')
data2.head(2)

  PROVINSI  Year  Unemployment Rate (%)  Laki-Laki  Perempuan
0     Aceh  2016                   7.57       7.05       8.44
1     Bali  2016                   1.89       2.17       1.55

# retrieve the dataset in 2020 and some columns that will be used for the dashboard

In [ ]:
d2=data2[data2["Year"]== 2020]
d2.columns=['Province','Year','Unemployment Rate (%)', 'Male','Female']
d2

                 Province  Year  Unemployment Rate (%)   Male  Female
140                  Aceh  2020                   6.59   6.06    7.47
141                  Bali  2020                   5.63   6.73    4.31
142                Banten  2020                  10.64  10.60   10.71
143              Bengkulu  2020                   4.07   4.10    4.03
144         Di Yogyakarta  2020                   4.57   5.37    3.64
145           Dki Jakarta  2020                  10.95  11.06   10.76
146             Gorontalo  2020                   4.28   4.53    3.86
147             Indonesia  2020                   7.07   8.98    6.46
148                 Jambi  2020                   5.13   4.44    6.34
149            Jawa Barat  2020                  10.46  10.91    9.67
150           Jawa Tengah  2020                   6.48   7.13    5.57
151            Jawa Timur  2020                   5.84   6.48    4.92
152      Kalimantan Barat  2020                   5.81   6.17    5.22
153    Kalimantan Selatan  2020                   4.74   5.13    4.15
154     Kalimantan Tengah  2020                   4.58   4.47    4.79
155      Kalimantan Timur  2020                   6.87   7.25    6.17
156      Kalimantan Utara  2020                   4.97   5.09    4.73
157  Kep. Bangka Belitung  2020                   5.25   4.90    5.90
158             Kep. Riau  2020                  10.34  10.87    9.38
159               Lampung  2020                   4.67   4.46    5.00
160                Maluku  2020                   7.57   8.02    6.91
161          Maluku Utara  2020                   5.15   5.19    5.08
162   Nusa Tenggara Barat  2020                   4.22   4.97    3.22
163   Nusa Tenggara Timur  2020                   4.28   4.59    3.89
164                 Papua  2020                   4.28   4.79    3.56
165           Papua Barat  2020                   6.80   7.40    5.83
166                  Riau  2020                   6.32   6.32    6.31
167        Sulawesi Barat  2020                   3.32   3.31    3.35
168      Sulawesi Selatan  2020                   6.31   6.68    5.74
169       Sulawesi Tengah  2020                   3.77   3.91    3.53
170     Sulawesi Tenggara  2020                   4.58   4.51    4.68
171        Sulawesi Utara  2020                   7.37   7.05    7.95
172        Sumatera Barat  2020                   6.88   6.79    6.99
173      Sumatera Selatan  2020                   5.51   5.48    5.54
174        Sumatera Utara  2020                   6.91   6.82    7.03

## choose other than row "indonesia" from the dataset

In [ ]:
unemployment = d2[d2['Province'] != 'Indonesia']
unemployment

                 Province  Year  Unemployment Rate (%)   Male  Female
140                  Aceh  2020                   6.59   6.06    7.47
141                  Bali  2020                   5.63   6.73    4.31
142                Banten  2020                  10.64  10.60   10.71
143              Bengkulu  2020                   4.07   4.10    4.03
144         DI Yogyakarta  2020                   4.57   5.37    3.64
145           DKI Jakarta  2020                  10.95  11.06   10.76
146             Gorontalo  2020                   4.28   4.53    3.86
148                 Jambi  2020                   5.13   4.44    6.34
149            Jawa Barat  2020                  10.46  10.91    9.67
150           Jawa Tengah  2020                   6.48   7.13    5.57
151            Jawa Timur  2020                   5.84   6.48    4.92
152      Kalimantan Barat  2020                   5.81   6.17    5.22
153    Kalimantan Selatan  2020                   4.74   5.13    4.15
154     Kalimantan Tengah  2020                   4.58   4.47    4.79
155      Kalimantan Timur  2020                   6.87   7.25    6.17
156      Kalimantan Utara  2020                   4.97   5.09    4.73
157  Kep. Bangka Belitung  2020                   5.25   4.90    5.90
158             Kep. Riau  2020                  10.34  10.87    9.38
159               Lampung  2020                   4.67   4.46    5.00
160                Maluku  2020                   7.57   8.02    6.91
161          Maluku Utara  2020                   5.15   5.19    5.08
162   Nusa Tenggara Barat  2020                   4.22   4.97    3.22
163   Nusa Tenggara Timur  2020                   4.28   4.59    3.89
164                 Papua  2020                   4.28   4.79    3.56
165           Papua Barat  2020                   6.80   7.40    5.83
166                  Riau  2020                   6.32   6.32    6.31
167        Sulawesi Barat  2020                   3.32   3.31    3.35
168      Sulawesi Selatan  2020                   6.31   6.68    5.74
169       Sulawesi Tengah  2020                   3.77   3.91    3.53
170     Sulawesi Tenggara  2020                   4.58   4.51    4.68
171        Sulawesi Utara  2020                   7.37   7.05    7.95
172        Sumatera Barat  2020                   6.88   6.79    6.99
173      Sumatera Selatan  2020                   5.51   5.48    5.54
174        Sumatera Utara  2020                   6.91   6.82    7.03

## Changing the writing of the province name to match the covid dataset so that it can be combined

In [ ]:
unemployment["Province"]=unemployment["Province"].replace(['Dki Jakarta','Di Yogyakarta'],['DKI Jakarta','DI Yogyakarta'])
unemployment

                 Province  Year  Unemployment Rate (%)   Male  Female
140                  Aceh  2020                   6.59   6.06    7.47
141                  Bali  2020                   5.63   6.73    4.31
142                Banten  2020                  10.64  10.60   10.71
143              Bengkulu  2020                   4.07   4.10    4.03
144         DI Yogyakarta  2020                   4.57   5.37    3.64
145           DKI Jakarta  2020                  10.95  11.06   10.76
146             Gorontalo  2020                   4.28   4.53    3.86
148                 Jambi  2020                   5.13   4.44    6.34
149            Jawa Barat  2020                  10.46  10.91    9.67
150           Jawa Tengah  2020                   6.48   7.13    5.57
151            Jawa Timur  2020                   5.84   6.48    4.92
152      Kalimantan Barat  2020                   5.81   6.17    5.22
153    Kalimantan Selatan  2020                   4.74   5.13    4.15
154     Kalimantan Tengah  2020                   4.58   4.47    4.79
155      Kalimantan Timur  2020                   6.87   7.25    6.17
156      Kalimantan Utara  2020                   4.97   5.09    4.73
157  Kep. Bangka Belitung  2020                   5.25   4.90    5.90
158             Kep. Riau  2020                  10.34  10.87    9.38
159               Lampung  2020                   4.67   4.46    5.00
160                Maluku  2020                   7.57   8.02    6.91
161          Maluku Utara  2020                   5.15   5.19    5.08
162   Nusa Tenggara Barat  2020                   4.22   4.97    3.22
163   Nusa Tenggara Timur  2020                   4.28   4.59    3.89
164                 Papua  2020                   4.28   4.79    3.56
165           Papua Barat  2020                   6.80   7.40    5.83
166                  Riau  2020                   6.32   6.32    6.31
167        Sulawesi Barat  2020                   3.32   3.31    3.35
168      Sulawesi Selatan  2020                   6.31   6.68    5.74
169       Sulawesi Tengah  2020                   3.77   3.91    3.53
170     Sulawesi Tenggara  2020                   4.58   4.51    4.68
171        Sulawesi Utara  2020                   7.37   7.05    7.95
172        Sumatera Barat  2020                   6.88   6.79    6.99
173      Sumatera Selatan  2020                   5.51   5.48    5.54
174        Sumatera Utara  2020                   6.91   6.82    7.03

In [ ]:
unemployment.shape
unemployment.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34 entries, 140 to 174
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Province               34 non-null     object
 1   Year                   34 non-null     int64
 2   Unemployment Rate (%)  34 non-null     float64
 3   Male                   34 non-null     float64
 4   Female                 34 non-null     float64
dtypes: float64(3), int64(1), object(1)
memory usage: 1.6+ KB

## combine the covid dataset and the unemployment dataset into one dataset using inner join

In [ ]:
##inner join data covid and data employment
merge=pd.merge(covid_data, unemployment, on='Province', how='inner')
#merge.shape
merge

,Province,Island,Total Cases,Total Deaths,Total Recovered,Population,Total Districts,Total Urban Villages,Total Rural Villages,Case Fatality Rate,Case Recovered Rate,Date,Year,Unemployment Rate (%),Male,Female
0,Aceh,Sumatera,8746,358,7139,5247257,289,0.0,6497.0,9.09%,90.00%,2020,2020,6.59,6.06,7.47
1,Bali,Nusa Tenggara,17593,516,16147,4216171,57,80.0,636.0,9.52%,92.85%,2020,2020,5.63,6.73,4.31
2,Banten,Jawa,18154,525,15656,10722374,155,313.0,1238.0,9.72%,99.65%,2020,2020,10.64,10.60,10.71
3,Bengkulu,Sumatera,3603,112,2556,1999539,129,172.0,1341.0,9.88%,83.46%,2020,2020,4.07,4.10,4.03
4,DI Yogyakarta,Jawa,12155,259,8176,3631015,78,46.0,392.0,9.86%,88.32%,2020,2020,4.57,5.37,3.64
5,DKI Jakarta,Jawa,183734,3270,164706,10846145,44,267.0,0.0,9.98%,95.74%,2020,2020,10.95,11.06,10.76
6,Gorontalo,Sulawesi,3841,104,3311,1180651,77,72.0,657.0,8.33%,96.67%,2020,2020,4.28,4.53,3.86
7,Jambi,Sumatera,3227,56,2318,3493357,141,163.0,1399.0,3.25%,81.29%,2020,2020,5.13,4.44,6.34
8,Jawa Barat,Jawa,90216,1446,74928,45161325,627,645.0,5312.0,6.87%,83.05%,2020,2020,10.46,10.91,9.67
9,Jawa Tengah,Jawa,82546,3627,56469,36364072,576,753.0,7809.0,90.91%,92.31%,2020,2020,6.48,7.13,5.57
10,Jawa Timur,Jawa,84410,6399,75050,40479023,666,777.0,7724.0,9.91%,93.73%,2020,2020,5.84,6.48,4.92
11,Kalimantan Barat,Kalimantan,3118,27,2744,5422814,174,99.0,2031.0,9.68%,99.44%,2020,2020,5.81,6.17,5.22
12,Kalimantan Selatan,Kalimantan,15303,584,13800,4023049,153,144.0,1864.0,9.92%,92.27%,2020,2020,4.74,5.13,4.15
13,Kalimantan Tengah,Kalimantan,9740,199,6487,2570289,136,139.0,1432.0,9.76%,89.39%,2020,2020,4.58,4.47,4.79
14,Kalimantan Timur,Kalimantan,27076,743,22807,3552191,103,197.0,841.0,6.25%,86.61%,2020,2020,6.87,7.25,6.17
15,Kalimantan Utara,Kalimantan,3794,57,2045,648407,53,35.0,447.0,6.25%,96.79%,2020,2020,4.97,5.09,4.73
16,Kep. Bangka Belitung,Sumatera,2338,35,1718,1379767,47,82.0,309.0,9.09%,96.08%,2020,2020,5.25,4.90,5.90
17,Kep. Riau,Sumatera,6995,171,6050,1929400,75,142.0,275.0,9.91%,90.06%,2020,2020,10.34,10.87,9.38
18,Lampung,Sumatera,6276,275,4318,9095591,228,205.0,2435.0,9.52%,85.37%,2020,2020,4.67,4.46,5.00
19,Maluku,Maluku,5722,71,4557,1847097,118,35.0,1198.0,8.70%,9.09%,2020,2020,7.57,8.02,6.91
20,Maluku Utara,Maluku,2771,89,2355,1307803,116,118.0,1063.0,9.60%,90.67%,2020,2020,5.15,5.19,5.08
21,Nusa Tenggara Barat,Nusa Tenggara,5664,261,4555,5270247,117,145.0,995.0,8.33%,9.87%,2020,2020,4.22,4.97,3.22
22,Nusa Tenggara Timur,Nusa Tenggara,2167,49,1204,5411321,309,327.0,3026.0,4.35%,9.52%,2020,2020,4.28,4.59,3.89
23,Papua,Papua,13209,156,7055,4340348,560,110.0,5411.0,8.75%,9.86%,2020,2020,4.28,4.79,3.56
24,Papua Barat,Papua,5979,99,5449,1140701,218,95.0,1742.0,7.69%,91.14%,2020,2020,6.80,7.40,5.83
25,Riau,Sumatera,24967,582,23079,6074100,169,268.0,1591.0,9.52%,92.61%,2020,2020,6.32,6.32,6.31
26,Sulawesi Barat,Sulawesi,1941,34,1551,1559984,69,73.0,575.0,3.45%,9.59%,2020,2020,3.32,3.31,3.35
27,Sulawesi Selatan,Sulawesi,31045,593,25750,9426885,311,792.0,2255.0,9.62%,90.44%,2020,2020,6.31,6.68,5.74
28,Sulawesi Tengah,Sulawesi,3552,106,1865,2955567,175,175.0,1842.0,9.38%,92.35%,2020,2020,3.77,3.91,3.53
29,Sulawesi Tenggara,Sulawesi,7907,147,6680,2635461,219,377.0,1911.0,7.41%,9.95%,2020,2020,4.58,4.51,4.68
30,Sulawesi Utara,Sulawesi,9670,310,7075,2641884,171,332.0,1507.0,9.99%,85.30%,2020,2020,7.37,7.05,7.95
31,Sumatera Barat,Sumatera,23464,525,21816,5519245,179,230.0,928.0,9.86%,93.37%,2020,2020,6.88,6.79,6.99
32,Sumatera Selatan,Sumatera,11826,599,9362,8217551,241,387.0,2853.0,9.09%,9.09%,2020,2020,5.51,5.48,5.54
33,Sumatera Utara,Sumatera,18149,679,15391,14874889,450,693.0,5417.0,9.91%,84.80%,2020,2020,6.91,6.82,7.03

In [ ]:
#merge.drop('Date', inplace=True, axis=1)
merge

,Province,Island,Total Cases,Total Deaths,Total Recovered,Population,Total Districts,Total Urban Villages,Total Rural Villages,Case Fatality Rate,Case Recovered Rate,Date,Year,Unemployment Rate (%),Male,Female
0,Aceh,Sumatera,8746,358,7139,5247257,289,0.0,6497.0,9.09%,90.00%,2020,2020,6.59,6.06,7.47
1,Bali,Nusa Tenggara,17593,516,16147,4216171,57,80.0,636.0,9.52%,92.85%,2020,2020,5.63,6.73,4.31
2,Banten,Jawa,18154,525,15656,10722374,155,313.0,1238.0,9.72%,99.65%,2020,2020,10.64,10.60,10.71
3,Bengkulu,Sumatera,3603,112,2556,1999539,129,172.0,1341.0,9.88%,83.46%,2020,2020,4.07,4.10,4.03
4,DI Yogyakarta,Jawa,12155,259,8176,3631015,78,46.0,392.0,9.86%,88.32%,2020,2020,4.57,5.37,3.64
5,DKI Jakarta,Jawa,183734,3270,164706,10846145,44,267.0,0.0,9.98%,95.74%,2020,2020,10.95,11.06,10.76
6,Gorontalo,Sulawesi,3841,104,3311,1180651,77,72.0,657.0,8.33%,96.67%,2020,2020,4.28,4.53,3.86
7,Jambi,Sumatera,3227,56,2318,3493357,141,163.0,1399.0,3.25%,81.29%,2020,2020,5.13,4.44,6.34
8,Jawa Barat,Jawa,90216,1446,74928,45161325,627,645.0,5312.0,6.87%,83.05%,2020,2020,10.46,10.91,9.67
9,Jawa Tengah,Jawa,82546,3627,56469,36364072,576,753.0,7809.0,90.91%,92.31%,2020,2020,6.48,7.13,5.57
10,Jawa Timur,Jawa,84410,6399,75050,40479023,666,777.0,7724.0,9.91%,93.73%,2020,2020,5.84,6.48,4.92
11,Kalimantan Barat,Kalimantan,3118,27,2744,5422814,174,99.0,2031.0,9.68%,99.44%,2020,2020,5.81,6.17,5.22
12,Kalimantan Selatan,Kalimantan,15303,584,13800,4023049,153,144.0,1864.0,9.92%,92.27%,2020,2020,4.74,5.13,4.15
13,Kalimantan Tengah,Kalimantan,9740,199,6487,2570289,136,139.0,1432.0,9.76%,89.39%,2020,2020,4.58,4.47,4.79
14,Kalimantan Timur,Kalimantan,27076,743,22807,3552191,103,197.0,841.0,6.25%,86.61%,2020,2020,6.87,7.25,6.17
15,Kalimantan Utara,Kalimantan,3794,57,2045,648407,53,35.0,447.0,6.25%,96.79%,2020,2020,4.97,5.09,4.73
16,Kep. Bangka Belitung,Sumatera,2338,35,1718,1379767,47,82.0,309.0,9.09%,96.08%,2020,2020,5.25,4.90,5.90
17,Kep. Riau,Sumatera,6995,171,6050,1929400,75,142.0,275.0,9.91%,90.06%,2020,2020,10.34,10.87,9.38
18,Lampung,Sumatera,6276,275,4318,9095591,228,205.0,2435.0,9.52%,85.37%,2020,2020,4.67,4.46,5.00
19,Maluku,Maluku,5722,71,4557,1847097,118,35.0,1198.0,8.70%,9.09%,2020,2020,7.57,8.02,6.91
20,Maluku Utara,Maluku,2771,89,2355,1307803,116,118.0,1063.0,9.60%,90.67%,2020,2020,5.15,5.19,5.08
21,Nusa Tenggara Barat,Nusa Tenggara,5664,261,4555,5270247,117,145.0,995.0,8.33%,9.87%,2020,2020,4.22,4.97,3.22
22,Nusa Tenggara Timur,Nusa Tenggara,2167,49,1204,5411321,309,327.0,3026.0,4.35%,9.52%,2020,2020,4.28,4.59,3.89
23,Papua,Papua,13209,156,7055,4340348,560,110.0,5411.0,8.75%,9.86%,2020,2020,4.28,4.79,3.56
24,Papua Barat,Papua,5979,99,5449,1140701,218,95.0,1742.0,7.69%,91.14%,2020,2020,6.80,7.40,5.83
25,Riau,Sumatera,24967,582,23079,6074100,169,268.0,1591.0,9.52%,92.61%,2020,2020,6.32,6.32,6.31
26,Sulawesi Barat,Sulawesi,1941,34,1551,1559984,69,73.0,575.0,3.45%,9.59%,2020,2020,3.32,3.31,3.35
27,Sulawesi Selatan,Sulawesi,31045,593,25750,9426885,311,792.0,2255.0,9.62%,90.44%,2020,2020,6.31,6.68,5.74
28,Sulawesi Tengah,Sulawesi,3552,106,1865,2955567,175,175.0,1842.0,9.38%,92.35%,2020,2020,3.77,3.91,3.53
29,Sulawesi Tenggara,Sulawesi,7907,147,6680,2635461,219,377.0,1911.0,7.41%,9.95%,2020,2020,4.58,4.51,4.68
30,Sulawesi Utara,Sulawesi,9670,310,7075,2641884,171,332.0,1507.0,9.99%,85.30%,2020,2020,7.37,7.05,7.95
31,Sumatera Barat,Sumatera,23464,525,21816,5519245,179,230.0,928.0,9.86%,93.37%,2020,2020,6.88,6.79,6.99
32,Sumatera Selatan,Sumatera,11826,599,9362,8217551,241,387.0,2853.0,9.09%,9.09%,2020,2020,5.51,5.48,5.54
33,Sumatera Utara,Sumatera,18149,679,15391,14874889,450,693.0,5417.0,9.91%,84.80%,2020,2020,6.91,6.82,7.03

In [ ]:
# from google.colab import files
# merge.to_csv('Covid-Unemployment2020.csv', index=True)
# files.download('Covid-Unemployment2020.csv')